# permissions for end users to view applicationdisruptionbudgets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: applicationdisruptionbudget-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: node-disruption-controller
    app.kubernetes.io/part-of: node-disruption-controller
    app.kubernetes.io/managed-by: kustomize
  name: applicationdisruptionbudget-viewer-role
rules:
- apiGroups:
  - nodedisruption.criteo.com
  resources:
  - applicationdisruptionbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nodedisruption.criteo.com
  resources:
  - applicationdisruptionbudgets/status
  verbs:
  - get
