# permissions for end users to edit nodedisruptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nodedisruption-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: node-disruption-controller
    app.kubernetes.io/part-of: node-disruption-controller
    app.kubernetes.io/managed-by: kustomize
  name: nodedisruption-editor-role
rules:
- apiGroups:
  - nodedisruption.criteo.com
  resources:
  - nodedisruptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodedisruption.criteo.com
  resources:
  - nodedisruptions/status
  verbs:
  - get
